### Numpy Library

- It is used for processing N-Dimensional array

In [4]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
rn=np.random.randint(0,100,size=5)
rn

array([91, 56, 56, 22, 69])

In [17]:

m3=np.random.randint(1,6,size=(4,3))
m3

array([[4, 5, 2],
       [4, 3, 3],
       [2, 1, 2],
       [2, 3, 1]])

In [19]:
m3[1][2]

3

In [24]:
m3=np.random.randint(0,2,size=(4,3,4))
m3

array([[[1, 0, 0, 1],
        [0, 1, 0, 0],
        [1, 1, 1, 0]],

       [[0, 1, 1, 1],
        [1, 1, 0, 1],
        [1, 0, 0, 1]],

       [[1, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 1, 0]],

       [[0, 1, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 0]]])

In [27]:
m3=np.random.randint(4,6,size=(3,3,3,3))
print(m3)
print(m3[2][2][2][1])

[[[[5 4 5]
   [4 5 5]
   [5 5 5]]

  [[5 5 4]
   [4 5 4]
   [4 5 4]]

  [[5 4 4]
   [5 5 4]
   [4 5 5]]]


 [[[5 5 5]
   [5 4 4]
   [4 4 5]]

  [[4 4 4]
   [5 5 4]
   [4 5 5]]

  [[5 4 4]
   [4 5 4]
   [5 5 5]]]


 [[[4 4 5]
   [4 5 4]
   [5 4 4]]

  [[4 4 5]
   [4 4 5]
   [5 5 5]]

  [[4 4 5]
   [5 4 4]
   [5 4 5]]]]
4


In [34]:
print(m3.ndim)
print(m3.size)
print(m3.shape)
print(m3.dtype)
print(m3.itemsize)
print(m3.nbytes)

4
81
(3, 3, 3, 3)
int32
4
324


### Pandas

Use Cases

* Data cleaning
* Data processing
* Data Analysis

Notatations
* Series
* DataFrames

In [3]:
import pandas as pd
internal1={'s1':21,'s2':18,'s3':24}
internal2={'s1':15,'s2':18,'s3':12}
internal2=pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [5]:
final={'Internal':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final

Internal  Internal2
s1        21         15
s2        18         18
s3        24         12

In [6]:
final.columns #Names of all columns

Index(['Internal', 'Internal2'], dtype='object')

In [7]:
final.values #Lists of all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [8]:
final.values[2,0]
final.values[2][0]

24

In [ ]:
for row in final.values:
    print('Internal1'-'+row[0]+','Internal')